### ISSUE TITLE
I know its under dev

### ISSUE THREAD

**Issue by VoxCeleste** [iiFlamiinBlaze/Selector#2]
It gives me this error
```Error: "Class 'iiFlamiinBlaze\events\PrisonTransfer' not found" (EXCEPTION) in "Selector-master/src/iiFlamiinBlaze/Selector" at line 65```

**Comment by iiFlamiinBlaze** [comment]
I'll take a look at it as soon as I can!

**Comment by iiFlamiinBlaze** [comment]
Commit: https://github.com/iiFlamiinBlaze/Selector/commit/ca3352d9c8f982e67a460355ff03b0901d450694

Fixed! Please note that the transfer events do not work yet, working on a fix for that :) Please report any other bugs (besides transfer events)! Thanks for the help :D 

Closing issue...
